// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class PingRequest {
  PingRequest({this.message});

  String? message;

  Object encode() {
    return <Object?>[message];
  }

  static PingRequest decode(Object result) {
    result as List<Object?>;
    return PingRequest(message: result[0] as String?);
  }
}

class PingResponse {
  PingResponse({this.message, this.timestampMs});

  String? message;

  int? timestampMs;

  Object encode() {
    return <Object?>[message, timestampMs];
  }

  static PingResponse decode(Object result) {
    result as List<Object?>;
    return PingResponse(
      message: result[0] as String?,
      timestampMs: result[1] as int?,
    );
  }
}

class VerifyRuntimeRequest {
  VerifyRuntimeRequest({this.sentinel});

  String? sentinel;

  Object encode() {
    return <Object?>[sentinel];
  }

  static VerifyRuntimeRequest decode(Object result) {
    result as List<Object?>;
    return VerifyRuntimeRequest(sentinel: result[0] as String?);
  }
}

class VerifyRuntimeResponse {
  VerifyRuntimeResponse({
    this.pythonVersion,
    this.mediahubVersion,
    this.timestampMs,
  });

  String? pythonVersion;

  String? mediahubVersion;

  int? timestampMs;

  Object encode() {
    return <Object?>[pythonVersion, mediahubVersion, timestampMs];
  }

  static VerifyRuntimeResponse decode(Object result) {
    result as List<Object?>;
    return VerifyRuntimeResponse(
      pythonVersion: result[0] as String?,
      mediahubVersion: result[1] as String?,
      timestampMs: result[2] as int?,
    );
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PingRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PingResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is VerifyRuntimeRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is VerifyRuntimeResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PingRequest.decode(readValue(buffer)!);
      case 130:
        return PingResponse.decode(readValue(buffer)!);
      case 131:
        return VerifyRuntimeRequest.decode(readValue(buffer)!);
      case 132:
        return VerifyRuntimeResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PythonApi {
  /// Constructor for [PythonApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PythonApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix =
           messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Phase 0 smoke call. Returns "pong" + a timestamp.
  Future<PingResponse> ping(PingRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.mediahub_python_bridge.PythonApi.ping$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PingResponse?)!;
    }
  }

  /// Phase 2 Feature #5: verifies the embedded Python runtime is alive
  /// and the `mediahub` module is importable. Returns the Python version
  /// + mediahub package version + a timestamp.
  Future<VerifyRuntimeResponse> verifyRuntime(
    VerifyRuntimeRequest request,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.mediahub_python_bridge.PythonApi.verifyRuntime$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VerifyRuntimeResponse?)!;
    }
  }
}
