// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mediahub.v2.python

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class PingRequest (
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PingRequest {
      val message = pigeonVar_list[0] as String?
      return PingRequest(message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PingResponse (
  val message: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PingResponse {
      val message = pigeonVar_list[0] as String?
      val timestampMs = pigeonVar_list[1] as Long?
      return PingResponse(message, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      message,
      timestampMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VerifyRuntimeRequest (
  val sentinel: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VerifyRuntimeRequest {
      val sentinel = pigeonVar_list[0] as String?
      return VerifyRuntimeRequest(sentinel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sentinel,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VerifyRuntimeResponse (
  val pythonVersion: String? = null,
  val mediahubVersion: String? = null,
  val timestampMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VerifyRuntimeResponse {
      val pythonVersion = pigeonVar_list[0] as String?
      val mediahubVersion = pigeonVar_list[1] as String?
      val timestampMs = pigeonVar_list[2] as Long?
      return VerifyRuntimeResponse(pythonVersion, mediahubVersion, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pythonVersion,
      mediahubVersion,
      timestampMs,
    )
  }
}
private open class PythonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PingRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PingResponse.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VerifyRuntimeRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VerifyRuntimeResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PingRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PingResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VerifyRuntimeRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VerifyRuntimeResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PythonApi {
  /** Phase 0 smoke call. Returns "pong" + a timestamp. */
  fun ping(request: PingRequest, callback: (Result<PingResponse>) -> Unit)
  /**
   * Phase 2 Feature #5: verifies the embedded Python runtime is alive
   * and the `mediahub` module is importable. Returns the Python version
   * + mediahub package version + a timestamp.
   */
  fun verifyRuntime(request: VerifyRuntimeRequest, callback: (Result<VerifyRuntimeResponse>) -> Unit)

  companion object {
    /** The codec used by PythonApi. */
    val codec: MessageCodec<Any?> by lazy {
      PythonApiPigeonCodec()
    }
    /** Sets up an instance of `PythonApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PythonApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mediahub_python_bridge.PythonApi.ping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PingRequest
            api.ping(requestArg) { result: Result<PingResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mediahub_python_bridge.PythonApi.verifyRuntime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VerifyRuntimeRequest
            api.verifyRuntime(requestArg) { result: Result<VerifyRuntimeResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
